#!/bin/bash



#Version
curl http://172.17.0.2:5000/version 

#

echo -ne "\nTrying logging with user $1 with password $2, press enter to continue..."
read press_enter

#Login
curl http:/10.0.2.3:5000/login -d '{"username":"'$t1'", "password":"'$t2'"}'

curl http://172.17.0.2:5000/signup -d '{"username":"p", "password":"p"}'

#Signup
curl http:/172.17.0.2:5000/signup -d '{"username":"prueba1", "password":"p"}'

#Crear
curl http:/172.17.0.2:5000/p/p -H "Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InAiLCJleHAiOjE2NzA5NTYzMzB9.WRph7h8bg3tx4nNitiWYTm1MwGyaCYcVkeOcUOFCepI" -d '{"doc_content": {"fruit": "Apple", "size": "Large", "color": "Red"}}' -X POST

#get file
curl http:/10.0.2.4:5000/p/p -H "Authorization: token $token"

#put
curl http:/10.0.2.4:5000/p/p -H "Authorization: token $token" -d '{"doc_content": {"fruit": "Apple", "size": "Small", "color": "Green", "flavour": "Bad"}}' -X PUT

#delete
curl http:/10.0.2.4:5000/p/p -H "Authorization: token $token" -X DELETE

#alldocs

ctrl+p ctrl+q
#Auth
curl http://10.0.2.4:5000/p/p -H "Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InAiLCJleHAiOjE2NzAzNTkyMDd9._Gz2zDC1YmpZI9nJNrGEzdfEjZzhJQTESw7sQW-IZtU"